name: subpred_deeplearning
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - cython
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - black
  - black-jupyter
  - ipykernel
  - joblib
  - matplotlib
  - seaborn
  - fastcluster
  - bioconda::cd-hit
  - bioconda::blast
  - openpyxl
  - ca-certificates
  - pigz
  - certifi
  - openssl
  - obonet
  - keras
  - tensorflow
  - pytorch
  - nvidia::cuda
  - transformers
  - sentencepiece
  - protobuf
  - jupyter
  - ipywidgets
  - mini3di
  - biopython
  - bioconda::foldseek
