name: subpred_deeplearning
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - cython
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - black
  - black-jupyter
  - ipykernel
  - joblib
  - matplotlib
  - seaborn
  - fastcluster
  - bioconda::cd-hit
  - bioconda::blast
  - openpyxl
  - ca-certificates
  - pigz
  - certifi
  - openssl
  - obonet
  - keras
  - tensorflow
  - pytorch
  - nvidia::cuda
  - transformers
  - sentencepiece
  - protobuf
  - jupyter
  - ipywidgets
  - mini3di
  - biopython
  - bioconda::foldseek
  # - conda-forge::yellowbrick
  # - conda-forge::imbalanced-learn
  # - flake8
  # - nbconvert
  # - jupyter
  # - conda-forge::owlready2
  # - venn
  # - mmseqs2
  # - gensim
  # - h5py
  # - tabulate
  # - pygraphviz
  # - pigz
  # - rdkit
  # - rpy2
  # - bioconductor-gosemsim
  # - r-future.apply
  # - bioconductor-org.sc.sgd.db
