name: dnn_cpu
channels:
  - conda-forge
dependencies:
  - python=3.12
  - seaborn=0.13.2
  - networkx=3.4.2
  - numpy=2.2.5
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - matplotlib=3.10.3
  - ipykernel
  - tensorflow-cpu=2.18.0
  - jinja2=3.1.6
