name: subpred_deeplearning
channels:
  - nvidia
  - bioconda
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - absl-py=2.2.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.18
  - aiosignal=1.3.2
  - alsa-lib=1.2.14
  - anyio=4.9.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - aria2=1.37.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-lru=2.0.5
  - attr=2.5.1
  - attrs=25.3.0
  - aws-c-auth=0.8.6
  - aws-c-cal=0.8.7
  - aws-c-common=0.12.0
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.4
  - aws-c-http=0.9.4
  - aws-c-io=0.17.0
  - aws-c-mqtt=0.12.2
  - aws-c-s3=0.7.13
  - aws-c-sdkutils=0.2.3
  - aws-checksums=0.2.3
  - aws-crt-cpp=0.31.0
  - aws-sdk-cpp=1.11.510
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - binutils=2.43
  - binutils_impl_linux-64=2.43
  - binutils_linux-64=2.43
  - biopython=1.85
  - black=25.1.0
  - black-jupyter=25.1.0
  - blast=2.16.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-compiler=1.9.0
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - cd-hit=4.8.1
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click=8.2.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.2
  - cpython=3.12.10
  - cuda=12.9.0
  - cuda-cccl_linux-64=12.9.27
  - cuda-command-line-tools=12.9.0
  - cuda-compiler=12.9.0
  - cuda-crt-dev_linux-64=12.9.41
  - cuda-crt-tools=12.9.41
  - cuda-cudart=12.9.37
  - cuda-cudart-dev=12.9.37
  - cuda-cudart-dev_linux-64=12.9.37
  - cuda-cudart-static=12.9.37
  - cuda-cudart-static_linux-64=12.9.37
  - cuda-cudart_linux-64=12.9.37
  - cuda-cuobjdump=12.9.26
  - cuda-cupti=12.9.19
  - cuda-cupti-dev=12.9.19
  - cuda-cuxxfilt=12.9.19
  - cuda-driver-dev=12.9.37
  - cuda-driver-dev_linux-64=12.9.37
  - cuda-gdb=12.9.19
  - cuda-libraries=12.9.0
  - cuda-libraries-dev=12.9.0
  - cuda-nsight=12.9.19
  - cuda-nvcc=12.9.41
  - cuda-nvcc-dev_linux-64=12.9.41
  - cuda-nvcc-impl=12.9.41
  - cuda-nvcc-tools=12.9.41
  - cuda-nvcc_linux-64=12.9.41
  - cuda-nvdisasm=12.9.19
  - cuda-nvml-dev=12.9.40
  - cuda-nvprof=12.9.19
  - cuda-nvprune=12.9.19
  - cuda-nvrtc=12.9.41
  - cuda-nvrtc-dev=12.9.41
  - cuda-nvtx=12.9.19
  - cuda-nvvm-dev_linux-64=12.9.41
  - cuda-nvvm-impl=12.9.41
  - cuda-nvvm-tools=12.9.41
  - cuda-nvvp=12.9.19
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.19
  - cuda-runtime=12.9.0
  - cuda-sanitizer-api=12.9.27
  - cuda-toolkit=12.9.0
  - cuda-tools=12.9.0
  - cuda-version=12.9
  - cuda-visual-tools=12.9.0
  - cudnn=9.10.0.56
  - curl=8.13.0
  - cxx-compiler=1.9.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - cython=3.1.0
  - datasets=3.6.0
  - dbus=1.13.6
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - double-conversion=3.3.1
  - entrez-direct=22.4
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.0
  - fastcluster=1.3.0
  - filelock=3.18.0
  - flatbuffers=24.12.23
  - foldseek=10.941cd33
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.0
  - fqdn=1.5.1
  - freetype=2.13.3
  - frozenlist=1.6.0
  - fsspec=2025.3.0
  - gast=0.6.0
  - gawk=5.3.1
  - gcc=13.3.0
  - gcc_impl_linux-64=13.3.0
  - gcc_linux-64=13.3.0
  - gds-tools=1.14.0.30
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpcio=1.67.1
  - gxx=13.3.0
  - gxx_impl_linux-64=13.3.0
  - gxx_linux-64=13.3.0
  - h11=0.16.0
  - h2=4.2.0
  - h5py=3.13.0
  - harfbuzz=11.2.1
  - hdf5=1.14.6
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - huggingface_hub=0.31.2
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=9.2.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.0
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - keras=3.9.2
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarrow=19.0.1
  - libarrow-acero=19.0.1
  - libarrow-dataset=19.0.1
  - libarrow-substrait=19.0.1
  - libasprintf=0.24.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.75
  - libcblas=3.9.0
  - libclang-cpp20.1=20.1.5
  - libclang13=20.1.5
  - libcrc32c=1.1.2
  - libcublas=12.9.0.13
  - libcublas-dev=12.9.0.13
  - libcudnn=9.10.0.56
  - libcudnn-dev=9.10.0.56
  - libcudss=0.5.0.16
  - libcufft=11.4.0.6
  - libcufft-dev=11.4.0.6
  - libcufile=1.14.0.30
  - libcufile-dev=1.14.0.30
  - libcups=2.3.3
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcurl=8.13.0
  - libcusolver=11.7.4.40
  - libcusolver-dev=11.7.4.40
  - libcusparse=12.5.9.5
  - libcusparse-dev=12.5.9.5
  - libdeflate=1.24
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-devel_linux-64=13.3.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.24.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.1
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgoogle-cloud=2.36.0
  - libgoogle-cloud-storage=2.36.0
  - libgpg-error=1.55
  - libgrpc=1.67.1
  - libhwloc=2.11.2
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm20=20.1.5
  - liblzma=5.8.1
  - libmagma=2.8.0
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libnpp=12.4.0.27
  - libnpp-dev=12.4.0.27
  - libnsl=2.0.1
  - libntlm=1.8
  - libnuma=2.0.18
  - libnvfatbin=12.9.19
  - libnvfatbin-dev=12.9.19
  - libnvjitlink=12.9.41
  - libnvjitlink-dev=12.9.41
  - libnvjpeg=12.4.0.16
  - libnvjpeg-dev=12.4.0.16
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.18.0
  - libopentelemetry-cpp-headers=1.18.0
  - libparquet=19.0.1
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.5
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsanitizer=13.3.0
  - libsentencepiece=0.2.0
  - libsodium=1.0.20
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=13.3.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=257.4
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libudev1=257.4
  - libunistring=0.9.10
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.9.2
  - libxkbfile=1.1.0
  - libxml2=2.13.8
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvm-openmp=20.1.5
  - lz4-c=1.10.0
  - markdown=3.8
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mini3di=0.2.1
  - mistune=3.1.3
  - mkl=2024.2.2
  - ml_dtypes=0.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.4.3
  - multiprocess=0.70.16
  - munkres=1.1.4
  - mypy_extensions=1.1.0
  - namex=0.0.9
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncbi-vdb=3.2.1
  - nccl=2.26.5.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nlohmann_json=3.12.0
  - notebook=7.4.2
  - notebook-shim=0.2.4
  - nsight-compute=2025.2.0.11
  - nspr=4.36
  - nss=3.111
  - numpy=2.2.5
  - obonet=1.1.1
  - ocl-icd=2.3.3
  - opencl-headers=2024.10.24
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openpyxl=3.1.5
  - openssl=3.5.0
  - opt_einsum=3.4.0
  - optree=0.15.0
  - orc=2.1.1
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pathspec=0.12.1
  - patsy=1.0.1
  - pcre2=10.45
  - perl=5.32.1
  - perl-archive-tar=2.40
  - perl-carp=1.50
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.202
  - perl-encode=3.21
  - perl-exporter=5.74
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-io-compress=2.201
  - perl-io-zlib=1.14
  - perl-json=4.10
  - perl-json-xs=4.03
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.243
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.69
  - perl-storable=3.15
  - perl-types-serialiser=1.01
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pigz=2.8
  - pillow=11.2.1
  - pip=25.1.1
  - pixman=0.46.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - prometheus-cpp=1.3.0
  - prometheus_client=0.22.0
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - propcache=0.3.1
  - protobuf=5.28.3
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=19.0.1
  - pyarrow-core=19.0.1
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pygments=2.19.1
  - pyparsing=3.2.3
  - pyside6=6.9.0
  - pysocks=1.7.1
  - python=3.12.10
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-flatbuffers=25.2.10
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.12
  - pytorch=2.6.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - qt6-main=6.9.0
  - rdma-core=57.0
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.36.2
  - regex=2024.11.6
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=14.0.0
  - rpds-py=0.25.0
  - rpsbproc=0.5.0
  - s2n=1.5.14
  - safetensors=0.5.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - sentencepiece=0.2.0
  - sentencepiece-python=0.2.0
  - sentencepiece-spm=0.2.0
  - setuptools=80.1.0
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.7
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - sympy=1.14.0
  - sysroot_linux-64=2.17
  - tbb=2021.13.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.18.0
  - tensorflow-base=2.18.0
  - tensorflow-estimator=2.18.0
  - termcolor=3.1.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tokenize-rt=6.1.0
  - tokenizers=0.21.1
  - tomli=2.2.1
  - tornado=6.5
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.51.3
  - triton=3.2.0
  - types-python-dateutil=2.9.0.20250516
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.4.0
  - wayland=1.23.1
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wget=1.21.4
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - wrapt=1.17.2
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xxhash=0.8.3
  - yaml=0.2.5
  - yarl=1.20.0
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
#   - pip:
#       - subpred==5.0.0
