name: dnn_cpu
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - comm=0.2.2
  - contourpy=1.3.2
  - cycler=0.12.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fonttools=4.58.1
  - freetype=2.13.3
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=9.3.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - joblib=1.5.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsodium=1.0.20
  - libsqlite=3.50.0
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - openjpeg=2.5.3
  - openssl=3.5.0
  - packaging=25.0
  - pandas=2.2.3
  - parso=0.8.4
  - patsy=1.0.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pyparsing=3.2.3
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pyzmq=26.4.0
  - qhull=2020.2
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.14.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zeromq=4.3.5
  - zipp=3.22.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.0
      - astunparse==1.6.3
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - flatbuffers==25.2.10
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.72.1
      - h5py==3.13.0
      - idna==3.10
      - keras==3.10.0
      - libclang==18.1.1
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - namex==0.1.0
      - numpy==2.1.3
      - opt-einsum==3.4.0
      - optree==0.16.0
      - protobuf==5.29.5
      - requests==2.32.3
      - rich==14.0.0
#       - subpred==5.0.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow-cpu==2.19.0
      - termcolor==3.1.0
      - urllib3==2.4.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
